//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteBook
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Brand { get; set; }
        public string Resolution { get; set; }
        public string Frequency { get; set; }
        public string Weight { get; set; }
    }
}
